# Generated by Django 4.2.26 on 2025-12-03 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Club",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("excerpt", models.TextField()),
                ("description", models.TextField()),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Private"), (1, "Public")], default=0
                    ),
                ),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "approved_members",
                    models.ManyToManyField(
                        blank=True,
                        related_name="club_members",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clubs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "unapproved_members",
                    models.ManyToManyField(
                        blank=True, related_name="waitlist", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-created_on"],
            },
        ),
    ]
