# Generated by Django 4.2.26 on 2025-12-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="club",
            old_name="description",
            new_name="club_briefing",
        ),
        migrations.RemoveField(
            model_name="club",
            name="status",
        ),
        migrations.AddField(
            model_name="club",
            name="expectations",
            field=models.TextField(default="test"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="club",
            name="is_private",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="club",
            name="max_members",
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AddField(
            model_name="club",
            name="organizer_email",
            field=models.EmailField(default="test", max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="club",
            name="organizer_name",
            field=models.CharField(default="test", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="club",
            name="personal_intro",
            field=models.TextField(default="test"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="club",
            name="prerequisites",
            field=models.TextField(default="test"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="club",
            name="require_approval",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="club",
            name="schedule_description",
            field=models.TextField(default="test"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="club",
            name="excerpt",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="club",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
